<a href="https://colab.research.google.com/github/velizabetho/mineria/blob/main/Clase_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

drivers = pd.read_csv("/content/drivers_updated.csv")
fl = pd.read_csv("/content/fastest_laps_updated.csv")
teams = pd.read_csv("/content/teams_updated.csv")
winners = pd.read_csv("/content/winners.csv")

In [ ]:
drivers.head()

  Pos                Driver Nationality          Car   PTS  year Code
0   1         Nino  Farina          ITA   Alfa Romeo  30.0  1950  FAR
1   2  Juan Manuel  Fangio          ARG   Alfa Romeo  27.0  1950  FAN
2   3       Luigi  Fagioli          ITA   Alfa Romeo  24.0  1950  FAG
3   4         Louis Rosier          FRA  Talbot-Lago  13.0  1950  ROS
4   5      Alberto  Ascari          ITA      Ferrari  11.0  1950  ASC

In [ ]:
drivers.shape

(1661, 7)

In [ ]:
drivers.isnull().sum()

Pos             0
Driver          0
Nationality     0
Car            11
PTS             0
year            0
Code            0
dtype: int64

In [ ]:
drivers['Nationality'].value_counts()

Nationality
GBR    299
ITA    193
FRA    185
GER    137
USA    135
BRA    111
FIN     65
AUS     51
ESP     51
AUT     44
NZL     38
BEL     36
ARG     35
JPN     35
SWE     33
SUI     31
MEX     30
NED     27
CAN     27
RSA     16
DEN     11
RUS     10
MON      9
THA      7
POL      7
VEN      6
COL      6
IND      5
POR      4
IRL      4
RHO      3
CHN      3
CHI      2
HUN      2
MAS      1
INA      1
RAF      1
Name: count, dtype: int64

In [ ]:
drivers['Nationality'].value_counts().count()

np.int64(37)

In [ ]:
drivers.describe()

               PTS         year
count  1661.000000  1661.000000
mean     31.138170  1987.124624
std      60.446033    21.849750
min       0.000000  1950.000000
25%       3.000000  1968.000000
50%       9.000000  1987.000000
75%      32.000000  2006.000000
max     575.000000  2024.000000

In [ ]:
fl.head()

,Grand Prix,Driver,Car,Time,year,Code
0,Great Britain,Nino Farina,Alfa Romeo,1:50.600,1950,FAR
1,Monaco,Juan Manuel Fangio,Alfa Romeo,1:51.000,1950,FAN
2,Indianapolis 500,Johnnie Parsons,Kurtis Kraft Offenhauser,NaN,1950,PAR
3,Switzerland,Nino Farina,Alfa Romeo,2:41.600,1950,FAR
4,Belgium,Nino Farina,Alfa Romeo,4:34.100,1950,FAR

In [ ]:
fl.isnull().sum()

Grand Prix    0
Driver        0
Car           0
Time          1
year          0
Code          0
dtype: int64

In [ ]:
fl['Grand Prix'].value_counts()

Grand Prix
Great Britain       74
Italy               74
Monaco              70
Belgium             67
Germany             64
France              62
Spain               53
Canada              52
Brazil              50
United States       39
Hungary             38
Australia           38
Japan               38
Austria             36
Netherlands         33
San Marino          26
Europe              23
Mexico              23
South Africa        23
Bahrain             20
Argentina           20
Malaysia            19
Portugal            18
China               17
Abu Dhabi           15
Singapore           14
Indianapolis 500    11
Turkey               9
USA West             8
Russia               8
Detroit              7
Sweden               6
Switzerland          6
Azerbaijan           6
USA East             5
South Korea          4
Emilia Romagna       4
Saudi Arabia         4
India                3
Miami                3
Styria               2
Qatar                2
Pacific              2
Caesar's Palace      2
Luxembourg           2
Morocco              1
Pescara              1
Dallas               1
70th Anniversary     1
Sakhir               1
Eifel                1
Tuscany              1
Las Vegas            1
Name: count, dtype: int64

In [ ]:
fl['Grand Prix'].value_counts().count()

np.int64(53)

In [ ]:
teams.head()

  Pos           Team   PTS  year
0   1        Vanwall  48.0  1958
1   2        Ferrari  40.0  1958
2   3  Cooper Climax  31.0  1958
3   4            BRM  18.0  1958
4   5       Maserati   6.0  1958

In [ ]:
teams.shape

(695, 4)

In [ ]:
teams.isnull().sum()

Pos     0
Team    0
PTS     0
year    0
dtype: int64

In [ ]:
teams['Team'].value_counts()

Team
Ferrari                  67
McLaren Mercedes         24
Renault                  23
Lotus Ford               19
Tyrrell Ford             19
                         ..
Red Bull Racing RBPT      1
AlphaTauri RBPT           1
AlphaTauri Honda RBPT     1
RB Honda RBPT             1
Kick Sauber Ferrari       1
Name: count, Length: 180, dtype: int64

In [ ]:
teams['Team'].value_counts().count()

np.int64(180)

In [ ]:
teams.describe()

              PTS         year
count  695.000000   695.000000
mean    70.191367  1992.133813
std    125.683887    18.337241
min      0.000000  1958.000000
25%      7.000000  1977.000000
50%     25.500000  1991.000000
75%     70.500000  2008.000000
max    860.000000  2024.000000

In [ ]:
winners.head()

,Grand Prix,Date,Winner,Car,Laps,Time,Name Code
0,Great Britain,1950-05-13,Nino Farina,Alfa Romeo,70.0,2:13:23.600,FAR
1,Monaco,1950-05-21,Juan Manuel Fangio,Alfa Romeo,100.0,3:13:18.700,FAN
2,Indianapolis 500,1950-05-30,Johnnie Parsons,Kurtis Kraft Offenhauser,138.0,2:46:55.970,PAR
3,Switzerland,1950-06-04,Nino Farina,Alfa Romeo,42.0,2:02:53.700,FAR
4,Belgium,1950-06-18,Juan Manuel Fangio,Alfa Romeo,35.0,2:47:26.000,FAN

In [ ]:
winners.isnull().sum()

Grand Prix    0
Date          0
Winner        0
Car           0
Laps          3
Time          3
Name Code     0
dtype: int64

In [ ]:
winners['Grand Prix'].value_counts()

Grand Prix
Great Britain       75
Italy               74
Monaco              69
Belgium             68
Germany             64
France              63
Spain               53
Canada              52
Brazil              50
United States       39
Hungary             38
Australia           38
Japan               38
Austria             36
Netherlands         33
San Marino          26
Europe              23
Mexico              23
South Africa        23
Argentina           21
Bahrain             20
Malaysia            19
Portugal            18
China               17
Abu Dhabi           15
Singapore           14
Indianapolis 500    11
Turkey               9
USA West             8
Russia               8
Detroit              7
Sweden               6
Switzerland          6
Azerbaijan           6
USA East             5
South Korea          4
Saudi Arabia         4
Miami                3
India                3
Emilia Romagna       3
Styria               2
Qatar                2
Pacific              2
Caesar's Palace      2
Luxembourg           2
Morocco              1
Pescara              1
Dallas               1
70th Anniversary     1
Sakhir               1
Eifel                1
Tuscany              1
Las Vegas            1
Name: count, dtype: int64

In [ ]:
winners['Grand Prix'].value_counts().count()

np.int64(53)

In [ ]:
winners.describe()

              Laps
count  1107.000000
mean     64.654020
std      20.267526
min       1.000000
25%      54.000000
50%      65.000000
75%      72.000000
max     200.000000